import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kiko Nunez Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <section className='bg-blue-900 min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl'>Kiko Nunez Portfolio</h1>
          <ul class="list-none flex items-center">
          <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>
          <li><a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-lg ml-8'> Resume </a></li>
        </ul>
        </nav>

      </section>

      </main>
    </div>
  )
}
